[package]
name = "x8"
version = "0.1.0"
authors = ["Alexander Mironov <sh1yo@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = "0.9.24"
regex = "1.3.7"
percent-encoding = "2.1.0"
lazy_static = "1.4.0"
clap = "2.33.1"
rand = "0.5.0"
colored = "2"
url = "2.1.1"
